spring.application.name=usuarioCursos
spring.datasource.url=jdbc:postgresql://localhost:5432/usuariosCursos
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jpa.hibernate.ddl-auto=validate